### ISSUE TITLE
Implementing React Query would clean up the fetchData function

### ISSUE THREAD

**Issue by wadehammes** [leonlarsson/the-finals-leaderboard#10]
https://github.com/leonlarsson/the-finals-leaderboard/blob/3ed785507cde15114aa3915d4a7e53c02e4a45bb/src/App.tsx#L55

Very cool implementation using the API, I think you could clean up a lot of the `fetchData` function by implementing React Query.

https://tanstack.com/query/latest/docs/react/overview

**Comment by wadehammes** [comment]
This would also solve https://github.com/leonlarsson/the-finals-leaderboard/issues/6 as React Query utilizes context to cache queries with the ability to invalidate them at any time.

**Comment by leonlarsson** [comment]
Great suggestion! I've just implemented it with https://github.com/leonlarsson/the-finals-leaderboard/commit/b6499a69ccc485fcdbf25baf5400e53aaddefe6f
