### ISSUE TITLE
After switching platform histroy is not being requested

### ISSUE THREAD

**Issue by Swackles** [leonlarsson/the-finals-leaderboard#12]
1. Click on user history in cross-play
2. Click on another platform
3. Go back to crossplay and click on the same user again, it will show "No data available"

**Comment by leonlarsson** [comment]
It looks like it is making a request, but the API returns no data.

Arkaik on Crossplay: https://api.finals-tracker.com/api/v1/users/leaderboard?name=Arkaik%239217&platform=crossplay
Arkaik on Steam: https://api.finals-tracker.com/api/v1/users/leaderboard?name=%40Arkaik__&platform=steam

**Comment by Swackles** [comment]
That is a seperate issue as well, the matching algorithm has a long way to go.

But when you do those steps, after going back, it doesn't even query data. Probably something to do with the table and how it caches data.

**Comment by leonlarsson** [comment]
Removing `response !== undefined` from https://github.com/leonlarsson/the-finals-leaderboard/blob/main/src/components/TableExpandedRow.tsx#L40 solves the issue of it not refetching.

But then we'd likely want to cache the response.

Janky implementation, but it works:
![2024-01-02_21-21-45](https://github.com/leonlarsson/the-finals-leaderboard/assets/54620188/df487f89-b684-4815-b825-25ed56a2c579)

Thoughts?

**Comment by Swackles** [comment]
Bad? That feels like a memory leak waiting to happen.

Tbh this entire behavior is kinda weird. Why and how does the data become an empty array? Does it carry over the rows from one render to another? But then even switching to steam should display the crossplay data, weird weird weird.

**Comment by leonlarsson** [comment]
When the leaderboard data is not ready, it's falling back on an empty array: https://github.com/leonlarsson/the-finals-leaderboard/blob/main/src/App.tsx#L213

Adding a key prop on DataTable consisting of the leaderboard version and platform removes the issue of not getting the chart data, but might introduce even more issues.

**Comment by Swackles** [comment]
But initial sate in the [leaderboard history](https://github.com/leonlarsson/the-finals-leaderboard/blob/main/src/components/TableExpandedRow.tsx#L25) is undefined, not an empty array. So that doesn't explain where the empty array comes from.

**Comment by leonlarsson** [comment]
Where do you see it being an empty array?

**Comment by Swackles** [comment]
It shows the "no data available" if the [`response?.data`](https://github.com/leonlarsson/the-finals-leaderboard/blob/main/src/components/TableExpandedRow.tsx#L72) is an empty array.

**Comment by leonlarsson** [comment]
"Fixed" by pausing the functionality. Let's revisit if Embark adds player IDs.
