### ISSUE TITLE
Investigate actual fame point brackets

### ISSUE THREAD

**Issue by leonlarsson** [leonlarsson/the-finals-leaderboard#7]
The official leaderboard and the game are inconsistent.

**Comment by leonlarsson** [comment]
Maybe solved with https://github.com/leonlarsson/the-finals-leaderboard/commit/99e85a6f37b0e604ce1a91237a3153e67d554b28

Keeping this open until I can fully confirm.

**Comment by Swackles** [comment]
I don't have bronze and silver league images anymore, but here are the gold, platinum and diamond.

The bronze ones and silver ones were taken from leagues and I put in [this](https://github.com/leonlarsson/the-finals-leaderboard/pull/1/commits/81272b61c96bcd1c5f2ab8f786786d2fc9059580) commit

![image](https://github.com/leonlarsson/the-finals-leaderboard/assets/25078482/487354e2-5752-40c8-9c39-1d0d1c92bd01)
![image](https://github.com/leonlarsson/the-finals-leaderboard/assets/25078482/b4c06a47-700c-49e9-a2e1-82bc6e88a2d3)
![image](https://github.com/leonlarsson/the-finals-leaderboard/assets/25078482/f97ddb5c-1dc7-4a16-ae09-f06d68fc3884)

**Comment by leonlarsson** [comment]
Season 2 has ditched fame points

**Comment by Swackles** [comment]
Yup, they also have ditched their old API (not being updated). I will be thinking whether I will just archive S1 or delete the data.

**Comment by leonlarsson** [comment]
I have a feeling they'll bring back some sort of progression based on their acknowledgement of the feedback

**Comment by Swackles** [comment]
whatever they'll do, I'll shut the tracker down for now. Don't have time to fix steam assignment anyway and without central id's provided by embark, no way to actually track player performance in the long term.

I'll still keep monitoring their endpoint, so if they ever start using that API again, I'll have the data.

**Comment by leonlarsson** [comment]
Understandable. Thanks for letting me know. I'll remove the History column from the leaderboard

**Comment by leonlarsson** [comment]
Closing for now.
